### ISSUE TITLE
Drop Rate: Green Linen Shirts

### ISSUE THREAD

**Issue by Prxie** [Prxie/CryptWoW-Bugs#3]
It is at duskwood Tranquil Gardens Cemetery
had 3 shirts dropped off 1 mob

**Comment by TheRealestMcCoy** [comment]
Was it from the mage or warrior. Looking at old loot tables it should not drop it is a crafted item.

http://wotlk-shoot.tauri.hu/?item=2579

If that is true then 
DELETE FROM `creature_loot_template` WHERE entry = 203 and item = 2579; 
DELETE FROM `creature_loot_template` WHERE entry = 48 and item = 2579;

**Comment by Prxie** [comment]
Removed Item:2579 (Green Linen Shirt) from loot_table.
