### ISSUE TITLE
Lost All Progress

### ISSUE THREAD

**Issue by KnightedEverhart** [Prxie/CryptWoW-Bugs#38]
Started playing on Thursday 4/19/2018 with the X5 xp boost.  Got to level 21 and got some decent gear from Shadowfang Keep. 

Came back today and all my Talent Points are refunded, Don't have any professions picked, All my spells/ abilities are gone except for the 2 that you start with on a Mage (Fireball & Frost Armor) no longer have the 6 slot bag I looted. Its like my mage was remade at level 21 without starting gear.

Not sure if I was already hacked or just a bug?

**Comment by ElyoQT** [comment]
happened to everyone, its called a rollback, they are still working on fixing it, hopefully you will get your items in the mail
