### ISSUE TITLE
Quest: The Wrong Stuff

### ISSUE THREAD

**Issue by Prxie** [Prxie/CryptWoW-Bugs#5]
not dropping the questitems from the mobs. Might be some loottable issue.

**Comment by Prxie** [comment]
Loot_template shows no items (20613 and 20614) in Database - needs to be added and tested.

**Comment by TheRealestMcCoy** [comment]
Try This 

`INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES (7149, 20613, -40, 1, 0, 1, 1);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES (7138, 20613, -25, 1, 0, 1, 1);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES (7139, 20613, -25, 1, 0, 1, 1);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES (7092, 20614, -25, 1, 0, 1, 1);`

**Comment by MrSolg** [comment]
> The Wrong Stuff

Updated tables to have drop chance be positive, as old values were -20 and -25 drop %. New values are 25.

Thank you for your report! And, @TheRealestMcCoy , thank you for the script! Gave me the items to look for!
