### ISSUE TITLE
NPC: UBRS Rend+Gyth

### ISSUE THREAD

**Issue by Prxie** [Prxie/CryptWoW-Bugs#7]
did not spawn during the event. Rend walked off but vanished.

**Comment by helicopter12** [comment]
[X] Fixed spawning of waves
[X] Adjusted waves to auto attack random targets

**Comment by helicopter12** [comment]
[X] Attempt at Rend TP fix

**Comment by Psychh** [comment]
Yeah he just runs to is mount and then dissapears.

**Comment by helicopter12** [comment]
Overall event now functions as I believe it should - Please leave comments of variations or issues you see and I will fix them!
